authapp/urls.py
from django.urls import path

from authapp import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login_page'),
    path('logout/', views.logout, name='logout'),
    path('sing_in/', views.sing_in, name='sing_in_page')
]

mainapp/urls.py
from django.urls import path

from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('comments/', views.comments_page, name='comments_page'),
    path('comment/<int:pk>', views.comment_page, name='comment_page'),
    path('comment/<int:pk>/<int:state>', views.comment_page, name='comment_page'),
    # path('comment/<int:pk>/<str:msg>', views.comment_page, name='comment_page'),
]

test_project_6/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Comment(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    desc = models.TextField(blank=False)
    image = models.ImageField(default='img/default.jpg', upload_to='img')

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return self.name

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class SingInForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.help_text = ''

authapp/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, SingInForm


def login(request):
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            auth.login(request=request, user=login_form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        login_form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'submit_title': 'войти',
        'form': login_form
    }
    return render(request, template_name='authapp/authentication.html', context=context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def sing_in(request):
    if request.method == 'POST':
        sing_in_form = SingInForm(data=request.POST)
        if sing_in_form.is_valid():
            sing_in_form.save()
            return HttpResponseRedirect(reverse('auth:login_page'))
    else:
        sing_in_form = SingInForm()
    context = {
        'page_title': 'регистрация',
        'submit_title': 'зарегистрироваться',
        'is_login': False,
        'form': sing_in_form,
    }
    return render(request, template_name='authapp/authentication.html', context=context)

mainapp/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse

from mainapp.models import Comment


def index(request):
    context = {
        'page_title': 'Главная',
    }
    return render(request, template_name='mainapp/index.html', context=context)


def comments_page(request):
    comments = Comment.objects.all()
    context = {
        'page_title': 'Отзывы',
        'comments': comments
    }
    return render(request, template_name='mainapp/comments_page.html', context=context)


def comment_page(request, pk, state=0):
    def make_json_response(comment):
        return JsonResponse({
            'url': reverse('main:comment_page', args=(comment.pk, )),
            'description': comment.desc
        })

    comment = Comment.objects.get(pk=pk)
    comment_name = 'comment-text-area'

    if request.method == 'GET' and comment_name in request.GET.keys():
        comment.desc = request.GET[comment_name]
        comment.save()

    if comment.user == request.user and state:
        return make_json_response(comment)
    # return make_json_response(comment)




    context = {
        'page_title': f'Комментарий «{comment.name}»',
        'item': comment,
        'back_url': request.META.get('HTTP_REFERER'),
        'state': state,
    }

    return render(request, template_name='mainapp/comment_page.html', context=context)

authapp/templates/authapp/authentication.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" title="{{ submit_title|default:'Войти'|capfirst }}">
        {% if is_login|default_if_none:True %}
            <a href="{% url 'auth:sing_in_page' %}">Регистрация</a>
        {% endif %}
    </form>
{% endblock %}

authapp/templates/authapp/base.html
{% extends 'root.html' %}

mainapp/templates/mainapp/base.html
{% extends 'root.html' %}
{% load static %}

{% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
{% endblock %}

mainapp/templates/mainapp/comment_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block alt_js %}
    <script src="{% static 'js/comment.js' %}"></script>
{% endblock %}

{% block content %}
    <h2>{{ item.name }}</h2>
    <p>{{ item.user.username }}:</p>
    <div class="comment-field">
        <p>{{ item.desc }}</p>
    </div>
    <img src="{{ item.image.url }}" width="200vh" alt="{{ item.image.url }} not found!">
    {% if user == item.user %}
        <a class="change-button" href="{% url 'main:comment_page' item.pk 1 %}">Изменить</a>
    {% endif %}
    <a href="{{ back_url }}">Назад</a>
{% endblock %}

mainapp/templates/mainapp/comments_page.html
{% extends 'mainapp/base.html' %}


{% block content %}
    <ul>
        {% for comment in comments %}
            <li>
                <a href="{% url 'mainapp:comment_page' comment.pk %}">{{ comment.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Это главная страница</h1>
{% endblock %}

templates/root.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:'главная'|capfirst }}</title>

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block alt_css %}
    {% endblock %}

    {% block js %}
    {% endblock %}

    {% block alt_js %}
    {% endblock %}
</head>
<body>
    <ul class="top-menu">
        <li>
            <a href="{% url 'main:index' %}">Главная</a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'main:comments_page' %}">Отзывы</a>
            </li>
            <li>
                <a href="{% url 'auth:logout' %}">Выход</a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'auth:login_page' %}">Вход</a>
            </li>
        {% endif %}
    </ul>

    {% block content %}
    {% endblock %}
</body>
</html>